先导入NumPy库

一般大家会写 import numpy as np

导入NumPy库给它一个别名np

这样使用这个库的任何东西时都可以输入np就可以调用NumPy,目的是打字更少更简洁

In [1]:
import numpy as np

创建一个数组,最直观的方法就是通过NumPy的array方法把列表转换为数组

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

简单的列表会被转换为一维数组

嵌套的列表会被转换为二维数组

最左边有几个方括号,他就会被转换为几维的数组

传入不同类型元素,虽然不报错,但是array方法会强制把它们转化为同一种类型,所以最好一开始还是传入同类元素

数组对象有一些属性
ndim会返回给我们数组的维度

In [4]:
print(arr1.ndim)
print(arr2.ndim)

1
2


shape会返回一个元组,表示各个维度的元素的个数

In [5]:
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)


size会返回给我们数组里面元素的总个数

In [6]:
print(arr1.size)
print(arr2.size)

3
6


dtype会返回给我们数组元组的类型 int64 64位整数

In [7]:
print(arr1.dtype)
print(arr2.dtype)

int64
int64


除了array方法,NumPy也提供其他创建数组的方法

zeros方法:创建元素全部为0的数组

In [9]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

ones方法:创建元素全部为1的数组

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

之所以这些数字后面都有小数点,是因为这些数字类型是浮点数,而不是整数

arange 创建元素为序列的方法

arange
表示针对array的range方法

里面传入的参数和range是一样的
结束值不会被包括在范围内

In [11]:
np.arange(5,10,2)

array([5, 7, 9])