#### concatenate

In [2]:
import numpy as np
arr1 = np.array([5,17,3,26,31])
arr2 = np.zeros(2)
np.concatenate([arr1,arr2])

array([ 5., 17.,  3., 26., 31.,  0.,  0.])

#### np.sort是函数 会返回排序好的新的数组,但是传入的原始数组不会被改变

In [3]:
import numpy as np
arr1 = np.array([5, 17, 3, 26, 31])
print(np.sort(arr1))
print(arr1)

[ 3  5 17 26 31]
[ 5 17  3 26 31]


#### 而数组的sort方法,会直接在数组上进行改动,把元素排序好。什么都不返回因为这时数组已经被改变,没必要返回了

In [4]:
import numpy as np
arr1 = np.array([5, 17, 3, 26, 31])
print(arr1.sort())
print(arr1)

None
[ 3  5 17 26 31]


#### 用索引获得元素

In [5]:
import numpy as np
arr1 = np.array([5, 17, 3, 26, 31])
print(arr1[0])
print(arr1[-2])
print(arr1[1:4])

5
26
[17  3 26]


#### 数组和数组进行运算

In [6]:
import numpy as np
arr4 = np.array([6, 7, 8, 9, 10])
arr5 = np.array([1, 1, 1, 1, 1])
print(arr4 + arr5)
print(arr4 - arr5)
print(arr4 * arr5)
print(arr4 / arr5)

[ 7  8  9 10 11]
[5 6 7 8 9]
[ 6  7  8  9 10]
[ 6.  7.  8.  9. 10.]


#### 数组和数字进行运算

In [7]:
import numpy as np
arr4 = np.array([6, 7, 8, 9, 10])
arr4 * 3

array([18, 21, 24, 27, 30])

In [8]:
import numpy as np
arr4 = np.array([6, 7, 8, 9, 10])
print(arr4.max())
print(arr4.min())
print(arr4.sum())
print(arr4.mean())

10
6
40
8.0


#### 根据特定条件从数组中筛选出值

In [9]:
import numpy as np
arr6 = np.array([-22, 3, 65, 9, 11, 7])
arr6[arr6 > 6]

array([65,  9, 11,  7])

#### 数组结合逻辑运算

In [10]:
import numpy as np
arr6 = np.array([-22, 3, 65, 9, 11, 7])
arr6[(arr6 > 6) & (arr6 < 10)]

array([9, 7])